// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALdwieOjj8qi2DDu3kvnfnPHXHFFv1E_s',
    appId: '1:628000271512:web:769c5d9f8ca0d31b25b4ed',
    messagingSenderId: '628000271512',
    projectId: 'lr16-firebase-auth-stanislav',
    authDomain: 'lr16-firebase-auth-stanislav.firebaseapp.com',
    storageBucket: 'lr16-firebase-auth-stanislav.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtihUwzCLHr18SphiWePIZBoC2pm84xuU',
    appId: '1:628000271512:android:c8455823ec5dd7c325b4ed',
    messagingSenderId: '628000271512',
    projectId: 'lr16-firebase-auth-stanislav',
    storageBucket: 'lr16-firebase-auth-stanislav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0rTWYD9sNbq8sA7KTR7zktT1slVu4v4',
    appId: '1:628000271512:ios:83578eb334da6e4725b4ed',
    messagingSenderId: '628000271512',
    projectId: 'lr16-firebase-auth-stanislav',
    storageBucket: 'lr16-firebase-auth-stanislav.firebasestorage.app',
    iosBundleId: 'com.example.lr17Firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0rTWYD9sNbq8sA7KTR7zktT1slVu4v4',
    appId: '1:628000271512:ios:83578eb334da6e4725b4ed',
    messagingSenderId: '628000271512',
    projectId: 'lr16-firebase-auth-stanislav',
    storageBucket: 'lr16-firebase-auth-stanislav.firebasestorage.app',
    iosBundleId: 'com.example.lr17Firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALdwieOjj8qi2DDu3kvnfnPHXHFFv1E_s',
    appId: '1:628000271512:web:19e5da20fffe25f425b4ed',
    messagingSenderId: '628000271512',
    projectId: 'lr16-firebase-auth-stanislav',
    authDomain: 'lr16-firebase-auth-stanislav.firebaseapp.com',
    storageBucket: 'lr16-firebase-auth-stanislav.firebasestorage.app',
  );
}
